version: "3.8"

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: r00t-password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspaces/devcontainer-sandbox
    command: sleep infinity

    network_mode: service:db

    depends_on:
      - db

volumes:
  mysql-data:
